name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Test
        run: npm test

      - name: Build
        run: npm run build